language: php

php:
  - 7.1

env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="127.0.0.1"
    - TYPO3_DATABASE_USERNAME="travis"
    - TYPO3_DATABASE_PASSWORD=""
    - typo3DatabaseName="typo3_ci"
    - typo3DatabaseHost="127.0.0.1"
    - typo3DatabaseUsername="travis"
    - typo3DatabasePassword=""

matrix:
  fast_finish: true

services:
  - mysql

install: make install

script:
  - make unitTests
  - make functionalTests

cache:
  directories:
    - $HOME/.composer/cache
